import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import Providers from "@/components/Providers";
import { Toaster } from "react-hot-toast";
import styles from "../styles/home.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="min-h-screen">
            
            <Header />
            <div className="mb-24">
            {children}

            </div>
            <Footer />
          </div>
        </Providers>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
